const types = [
  "Canine",
  "Feline",
  "Bird",
  "Reptile",
  "Rodent",
  "Amphibian",
  "Equine",
  "Fish",
  "Rabbit",
  "Hedgehog",
  "Other",
];

const dogBreeds = [
  "Akita",
  "American Bulldog",
  "Australian Cattle Dog",
  "Australian Shepherd",
  "Basenji",
  "Basset Hound",
  "Beagle",
  "Beauceron",
  "Bedlington Terrier",
  "Belgian Malinois",
  "Belgian Sheepdog",
  "Belgian Tervuren",
  "Bernese Mountain Dog",
  "Bichon Frise",
  "Black and Tan Coonhound",
  "Black Russian Terrier",
  "Bloodhound",
  "Border Collie",
  "Border Terrier",
  "Boston Terrier",
  "Boxer",
  "Bracco Italiano",
  "Briard",
  "Brittany",
  "Bull Terrier",
  "Bulldog",
  "Bullmastiff",
  "Cairn Terrier",
  "Canaan Dog",
  "Cane Corso",
  "Cavalier King Charles Spaniel",
  "Chesapeake Bay Retriever",
  "Chihuahua",
  "Chinese Crested",
  "Chinese Shar-Pei",
  "Chow Chow",
  "Cocker Spaniel",
  "Collie",
  "Coonhound",
  "Dachshund",
  "Dalmatian",
  "Doberman Pinscher",
  "Dogo Argentino",
  "Dogue de Bordeaux",
  "English Bulldog",
  "English Cocker Spaniel",
  "English Foxhound",
  "English Springer Spaniel",
  "English Toy Spaniel",
  "Flat-Coated Retriever",
  "French Bulldog",
  "German Pinscher",
  "German Shepherd Dog",
  "German Shorthaired Pointer",
  "German Wirehaired Pointer",
  "Giant Schnauzer",
  "Glen of Imaal Terrier",
  "Goldador",
  "Golden Retriever",
  "Goldendoodle",
  "Gordon Setter",
  "Great Dane",
  "Great Pyrenees",
  "Greater Swiss Mountain Dog",
  "Havanese",
  "Irish Setter",
  "Irish Terrier",
  "Irish Water Spaniel",
  "Italian Greyhound",
  "Japanese Chin",
  "Keeshond",
  "Labrador Retriever",
  "Lagotto Romagnolo",
  "Lakeland Terrier",
  "Lhasa Apso",
  "Maltese",
  "Mastiff",
  "Miniature Bull Terrier",
  "Miniature Pinscher",
  "Miniature Schnauzer",
  "Newfoundland",
  "Norwegian Buhund",
  "Norwegian Elkhound",
  "Nova Scotia Duck Tolling Retriever",
  "Old English Sheepdog",
  "Otterhound",
  "Papillon",
  "Pekingese",
  "Pembroke Welsh Corgi",
  "Pit Bull Terrier",
  "Pointer",
  "Pomeranian",
  "Poodle (Standard, Miniature, Toy)",
  "Portuguese Water Dog",
  "Rottweiler",
  "Saint Bernard",
  "Saluki",
  "Samoyed",
  "Schipperke",
  "Scottish Deerhound",
  "Scottish Terrier",
  "Sealyham Terrier",
  "Shetland Sheepdog",
  "Shiba Inu",
  "Shih Tzu",
  "Siberian Husky",
  "Staffordshire Bull Terrier",
  "Standard Schnauzer",
  "Sussex Spaniel",
  "Tibetan Mastiff",
  "Tibetan Spaniel",
  "Tibetan Terrier",
  "Vizsla",
  "Weimaraner",
  "Welsh Springer Spaniel",
  "Welsh Terrier",
  "West Highland White Terrier",
  "Whippet",
  "Wire Fox Terrier",
  "Wirehaired Pointing Griffon",
  "Yorkshire Terrier",
  "Mixed",
  "Other",
];

const catBreeds = [
  "Abyssinian",
  "American Bobtail",
  "American Curl",
  "American Shorthair",
  "American Wirehair",
  "Balinese",
  "Bengal",
  "Birman",
  "British Shorthair",
  "Burmese",
  "Chartreux",
  "Cornish Rex",
  "Devon Rex",
  "Egyptian Mau",
  "European Burmese",
  "Havana Brown",
  "Himalayan",
  "Japanese Bobtail",
  "Khao Manee",
  "Kurilian Bobtail",
  "Maine Coon",
  "Manx",
  "Norwegian Forest Cat",
  "Oriental Shorthair",
  "Persian",
  "Ragdoll",
  "Russian Blue",
  "Scottish Fold",
  "Siamese",
  "Siberian",
  "Singapura",
  "Snowshoe",
  "Somali",
  "Sphynx",
  "Turkish Angora",
  "Turkish Van",
  "Burmilla",
  "Other",
];

const birdBreeds = [
  "African Grey Parrot",
  "Amazon Parrot",
  "Budgerigar (Budgie)",
  "Cockatiel",
  "Cockatoo",
  "Conure",
  "Dove",
  "Eclectus Parrot",
  "Finch",
  "Lovebird",
  "Macaw",
  "Parakeet",
  "Quaker Parrot",
  "Ringneck Parakeet",
  "Rosella",
  "Senegal Parrot",
  "Canary",
  "Pionus Parrot",
  "Zebra Finch",
  "Other",
];

const reptileBreeds = [
  "Bearded Dragon",
  "Ball Python",
  "Leopard Gecko",
  "Corn Snake",
  "Red-Eared Slider",
  "African Grey Horned Chameleon",
  "Blue-Tongue Skink",
  "Iguana",
  "Russian Tortoise",
  "Green Tree Frog",
  "Box Turtle",
  "Crested Gecko",
  "Chinese Water Dragon",
  "Honduran Milksnake",
  "Fat-Tailed Gecko",
  "Other",
];

const rodentBreeds = [
  "Hamster",
  "Gerbil",
  "Guinea Pig",
  "Mouse",
  "Rat",
  "Chinchilla",
];

const amphibianBreeds = [
  "Frog",
  "Toad",
  "Salamander",
  "Newt",
  "Axolotl",
  "Other",
];

const equineBreeds = [
  "Arabian",
  "Thoroughbred",
  "Quarter Horse",
  "Appaloosa",
  "Paint",
  "Warmblood",
  "Tennessee Walking Horse",
  "Clydesdale",
  "Friesian",
  "Shetland Pony",
  "Welsh Pony",
  "Percheron",
  "Hanoverian",
  "Morgan",
  "Lipizzaner",
  "Mustang",
  "Icelandic Horse",
  "Other",
];

const fishBreeds = [
  "Betta",
  "Goldfish",
  "Guppy",
  "Angelfish",
  "Neon Tetra",
  "Zebra Danio",
  "Corydoras Catfish",
  "Mollies",
  "Swordtail",
  "Platies",
  "Discus",
  "Oscar",
  "Koi",
  "Siamese Fighting Fish",
  "Rainbowfish",
  "Clownfish",
  "Shubunkin",
  "Other",
];

const rabbitBreeds = [
  "American",
  "American Fuzzy Lop",
  "American Sable",
  "Angora",
  "Belgian Hare",
  "Britannia Petite",
  "Cavalier",
  "Champagne d'Argent",
  "Dutch",
  "English Angora",
  "English Spot",
  "Flemish Giant",
  "Holland Lop",
  "Mini Rex",
  "Netherland Dwarf",
  "New Zealand",
  "Palomino",
  "Rex",
  "Silver",
  "Silver Marten",
  "Teddy",
  "Thrianta",
];

const breedOptions = {
  Canine: dogBreeds,
  Feline: catBreeds,
  Bird: birdBreeds,
  Reptile: reptileBreeds,
  Rodent: rodentBreeds,
  Amphibian: amphibianBreeds,
  Equine: equineBreeds,
  Fish: fishBreeds,
  Rabbit: rabbitBreeds,
  Hedgehog: [],
  Other: [],
};

export {
  types,
  dogBreeds,
  catBreeds,
  birdBreeds,
  reptileBreeds,
  rodentBreeds,
  amphibianBreeds,
  equineBreeds,
  fishBreeds,
  rabbitBreeds,
  breedOptions,
};
